"""remove title from projects

Revision ID: 1e2d209b92bd
Revises: 1f908f249595
Create Date: 2025-09-14 16:25:54.098272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e2d209b92bd'
down_revision: Union[str, Sequence[str], None] = '1f908f249595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consulting_work', 'employer_name',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('consulting_work', 'position',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('education', 'degree_type',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('education', 'university_name',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('profiles', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('profiles', 'profession',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('profiles', 'email',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('profiles', 'github_link',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('profiles', 'linkedin_link',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('profiles', 'summary_text',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('projects', 'title')
    op.alter_column('work_experiences', 'employer_name',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('work_experiences', 'position',
               existing_type=mysql.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'position',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('work_experiences', 'employer_name',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('title', mysql.TEXT(), nullable=False))
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('profiles', 'summary_text',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'linkedin_link',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'github_link',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('profiles', 'profession',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('profiles', 'name',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('education', 'university_name',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('education', 'degree_type',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('consulting_work', 'position',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('consulting_work', 'employer_name',
               existing_type=sa.Text(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
